### ISSUE TITLE
Add to OpenVPN walkthrough

### ISSUE THREAD

**Issue by joncamfield** [Pluggable-Transports/Pluggable-Transports-website#12]
Make a VPN walkthrough more aimed at commercial clients (i.e. not using tun / socks layer)

**Comment by dlshad** [comment]
Not sure if it's a good idea to improve the walkthrough we have currently or create new one? @joncamfield

**Comment by joncamfield** [comment]
Let's base this on your current interactions with VPN developers; do they want IPC, API, or... ?

**Comment by yamuk** [comment]
A new OpenVPN walkthrough with obfs4 would be nice.

**Comment by joncamfield** [comment]
The walkthrough now uses obfs4: https://www.pluggabletransports.info/implement/openvpn/
