### ISSUE TITLE
Create tutorial on how to add censorship resistance to mobile apps

### ISSUE THREAD

**Issue by fortuna** [Pluggable-Transports/Pluggable-Transports-website#15]
It would be awesome to have a step-by-step tutorial on how you can convert an Android app and backend to use Pluggable Transports. I know there's [Pluto](https://github.com/guardianproject/pluto), but you have to dig a lot of documentation to have any idea whether that will work for you. A tutorial would significantly lower that barrier and show publishers what is possible in a more concrete way.

Such a tutorial could become a reference to anyone wanting to add censorship resistance to their apps. What's great about catering to publishers is that they control both the client and the server, so they are in the best position to plug different transports to their flow

**Comment by joncamfield** [comment]
This is great feedback - we just posted a general walkthrough of implementing via the Go API  (https://www.pluggabletransports.info/implement/go/) and have a table cross-referencing tools currently available on what platforms (https://www.pluggabletransports.info/implement/) but will also work to get this focused guide out for Android apps

Thanks!
