### ISSUE TITLE
PT doesn't allow chaining of forward proxies

### ISSUE THREAD

**Issue by fortuna** [Pluggable-Transports/Pluggable-Transports-website#26]
As far as I can tell, you can't chain proxies using PT. Is that true? If not, how is that done?
Are there plans to address it?

**Comment by joncamfield** [comment]
Thanks for the issue - we actually just launched https://github.com/Pluggable-Transports/Pluggable-Transports-spec (currently a stub) -- but it will be the place to discuss spec work.  Could you ask this question over there?
